image: gcc:latest

stages:
  - build
  - test

build:
  stage: build
  before_script: 
    - apt update && apt -y install cmake libeigen3-dev
  script: 
    - mkdir build
    - cd build
    - cmake ..
    - make
  artifacts:
    paths:
      - build/src/pbcpp/libpbcpp.so
      - build/tests/unittests

  # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
  # cache:
  #   paths:
  #     - "*.o"

# run tests using the binary built before
test:
  stage: test
  #cache:
  #  paths:
  #  - build/
  dependencies: 
    - build
  script:
    - ls
    - build/tests/unittests
