image: gcc:latest

stages:
  - build
  - test


build-debug:
  stage: build
  before_script: 
    - apt update && apt -y install cmake libeigen3-dev
  script: 
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug
    - make VERBOSE=1
  cache:
    key: build-cache
    #untracked: true
    paths:
      - build/
    policy: push
  #artifacts:
  #  paths:
  #    - build/src/pbcpp/libpbcpp.so
  #    - build/tests/unittests


# run tests using the binary built before
test:
  stage: test
  dependencies: 
    - build-debug
  cache:
    key: build-cache
    #untracked: true
    paths:
      - build/
    policy: pull-push
  before_script: 
    - apt update && apt -y install tree lcov
  script:
    - tree build/
    - cd build
    - tests/unittests
    - lcov --capture --directory src/pbcpp/CMakeFiles/pbcpp.dir/ --output-file coverage_all.info
    - lcov --extract coverage_all.info "*/src/pbcpp/*" --output-file coverage_pbcpp.info
  coverage: '/lines......:\s*(\d+.\d+\%)/'
