image: gcc:latest

stages:
  - build
  - test

build-debug:
  stage: build
  before_script: 
    - apt update && apt -y install cmake libeigen3-dev
  script: 
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug
    - make VERBOSE=1
  artifacts:
    paths:
      - build/src/pbcpp/libpbcpp.so
      - build/tests/unittests

  # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
  # cache:
  #   paths:
  #     - "*.o"

# run tests using the binary built before
test:
  stage: test
  #cache:
  #  paths:
  #  - build/
  dependencies: 
    - build-debug
  script:
    - ls
    - build/tests/unittests
